### ISSUE TITLE
Failed to load the markdown-table-editor package

### ISSUE THREAD

**Issue by haozan** [susisu/markdown-table-editor#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [markdown-table-editor](https://github.com/susisu/markdown-table-editor) package 0.5.0

### Stack Trace

Failed to load the markdown-table-editor package

```
At Unexpected token } in JSON at position 303

SyntaxError: Unexpected token } in JSON at position 303
    at Object.parse (native)
    at parseObject (/app.asar/node_modules/season/lib/cson.js:54:19)
    at parseContentsSync (/app.asar/node_modules/season/lib/cson.js:68:16)
    at Object.readFileSync (/app.asar/node_modules/season/lib/cson.js:170:14)
    at /app.asar/src/package.js:439:38
    at Array.map (native)
    at Package.module.exports.Package.loadKeymaps (/app.asar/src/package.js:436:46)
    at /app.asar/src/package.js:114:19
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:792:28
```

### Commands

```
```

### Non-Core Packages

```
atom-smart-template 0.3.2 
language-markdown 0.20.0 
markdown-image-paste 2.5.2 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
markdown-table-editor 0.5.0 
markdown-themeable-pdf 1.2.0 
markdown-toc 0.4.2 
markdown-writer 2.6.4 
pdf-view 0.57.0 
ruby-block 0.3.6 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
tool-bar-markdown-writer 0.2.0 
```

**Comment by susisu** [comment]
It seems that the keymap file is broken, but as far as I confirmed there are no problem.
Have you edited `~/.atom/packages/markdown-table-editor/keymaps/markdown-table-editor.json`?
