### ISSUE TITLE
Failed to activate the markdown-table-editor package

### ISSUE THREAD

**Issue by sophiayang1997** [susisu/markdown-table-editor#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [markdown-table-editor](https://github.com/susisu/markdown-table-editor) package 0.5.2

### Stack Trace

Failed to activate the markdown-table-editor package

```
At Cannot find module 'meaw'

Error: Cannot find module 'meaw'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.0/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.0/resources/app/src/native-compile-cache.js:66:1)
    at /packages/markdown-table-editor/lib/table.js:3:36)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.0/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.17.0/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.0/resources/app/src/native-compile-cache.js:66:1)
    at /packages/markdown-table-editor/lib/editor-controller.js:3:57)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.0/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.17.0/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.0/resources/app/src/native-compile-cache.js:66:1)
    at /packages/markdown-table-editor/lib/controller.js:3:43)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.0/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.17.0/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.0/resources/app/src/native-compile-cache.js:66:1)
    at /packages/markdown-table-editor/lib/markdown-table-editor.js:11:21)
```

### Commands

```
```

### Non-Core Packages

```
pdf-view 0.58.0 
language-markdown 0.22.0 
markdown-image-paste 2.5.2 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
markdown-table-editor 0.5.2 
markdown-themeable-pdf 1.2.0 
node_modules undefined 
```

**Comment by susisu** [comment]
> Error: Cannot find module 'meaw'

It seems that a dependency was not installed correctly or is broken.

Please uninstall and reinstall `markdown-table-editor` package.
Then does the same problem still occur?

**Comment by sophiayang1997** [comment]
I installed markdown-table-editor by reinstalling it.Thank you very much!

At 2017-05-21 16:01:49, "Susisu" <notifications@github.com> wrote:


Error: Cannot find module 'meaw'

It seems that a dependency was not installed correctly or is broken.

Please uninstall and reinstall markdown-table-editor package.
Then does the same problem still occur?
