### ISSUE TITLE
Uncaught TypeError: Cannot read property 'copy' of undefined

### ISSUE THREAD

**Issue by ethancfchen** [susisu/markdown-table-editor#4]
[Enter steps to reproduce:]

1. Select a table
1. Use command palette `Markdown Table Editor: Align Left`
1. Get the error

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [markdown-table-editor](https://github.com/susisu/markdown-table-editor) package 0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'copy' of undefined

```
At /Users/ethancfchen/.atom/packages/markdown-table-editor/lib/editor-controller.js:303

TypeError: Cannot read property 'copy' of undefined
    at EditorController.align (/packages/markdown-table-editor/lib/editor-controller.js:303:69)
    at EditorController.alignLeft (/packages/markdown-table-editor/lib/editor-controller.js:335:10)
    at /packages/markdown-table-editor/lib/controller.js:35:22
    at /packages/markdown-table-editor/lib/controller.js:97:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -9:06.6.0 core:confirm (input.hidden-input)
     -0:28.8.0 command-palette:toggle (input.hidden-input)
     -0:26.1.0 core:confirm (input.hidden-input)
     -0:26.1.0 markdown-table-editor:format (input.hidden-input)
     -0:22 command-palette:toggle (input.hidden-input)
  2x -0:18.8.0 core:backspace (input.hidden-input)
     -0:12.9.0 core:confirm (input.hidden-input)
     -0:12.9.0 markdown-table-editor:format (input.hidden-input)
     -0:08.5.0 command-palette:toggle (input.hidden-input)
  9x -0:05.9.0 core:move-down (input.hidden-input)
     -0:02.3.0 core:confirm (input.hidden-input)
     -0:02.3.0 markdown-table-editor:align-left (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.3 
aligner-javascript 1.2.0 
atom-beautify 0.30.4 
atom-css-clean 2.21.0 
atom-easy-jsdoc 4.12.1 
busy-signal 1.4.3 
caniuse 0.9.2 
change-case 0.6.5 
comment-headers 2.15.0 
css-snippets 1.1.0 
dash 1.7.1 
editorconfig 2.2.2 
emmet 2.4.3 
es6-javascript 1.0.0 
es6-snippets 0.3.0 
file-icons 2.1.9 
filesize 3.0.0 
git-log 0.4.1 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
html-entitize 1.1.0 
intentions 1.1.2 
javascript-snippets 1.2.1 
language-babel 2.67.0 
language-dot 1.7.0 
language-javascript-jsx 0.3.7 
language-markdown 0.25.1 
language-plantuml 0.2.0 
language-pug 0.0.21 
language-svg 0.9.2 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-annotations 1.0.1 
linter-eslint 8.2.1 
linter-js-yaml 1.2.7 
linter-jsonlint 1.3.0 
linter-markdown 4.1.0 
linter-phpcs 1.6.7 
linter-pug 1.3.1 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.3 
linter-xo 0.23.1 
markdown-preview-plus 2.4.10 
markdown-table-editor 0.6.0 
markdown-writer 2.6.5 
merge-conflicts 1.4.5 
minimap 4.29.0 
minimap-highlight-selected 4.6.1 
open-in-browser 0.5.2 
open-terminal-here 2.3.1 
php-getters-setters 0.5.5 
php-integrator-refactoring 1.4.0 
pigments 0.39.1 
plantuml-viewer 0.7.2 
platformio-ide-terminal 2.5.3 
project-manager 3.3.5 
regex-railroad-diagram 0.19.3 
script 3.15.0 
split-diff 1.4.3 
Sublime-Style-Column-Selection 1.7.4 
svg-preview 0.11.0 
sync-settings 0.8.2 
tabs-to-spaces 1.0.3 
text-pastry 0.6.1 
todo-show 1.11.0 
tree-view-git-status 1.4.0 
```

**Comment by susisu** [comment]
Thank you for reporting!

I confirmed that this problem happens when you try to align a column but the cursor is out of the table.
This will be fixed in v0.6.1.
